=== MrLoick/architecturerules/tags/2.0.1-rc2/src/main/resources/architecture-rules.dtd
<!DOCTYPE architecture [
        <!ELEMENT packages (package)*>
        <!ELEMENT architecture (configuration|rules)*>
        <!ELEMENT sources (source)*>
        <!ATTLIST sources
                no-packages CDATA #REQUIRED>
        <!ELEMENT rule (comment|packages|violations)*>
        <!ATTLIST rule
                id CDATA #REQUIRED>
        <!ELEMENT violations (violation)*>
        <!ELEMENT rules (rule)*>
        <!ELEMENT violation (#PCDATA)>
        <!ELEMENT configuration (sources|cyclicalDependency)*>
        <!ELEMENT comment (#PCDATA)>
        <!ELEMENT source (#PCDATA)>
        <!ATTLIST source
                not-found CDATA #REQUIRED>
        <!ELEMENT package (#PCDATA)>
        <!ELEMENT cyclicalDependency (#PCDATA)>
        <!ATTLIST cyclicalDependency
                test CDATA #REQUIRED>
        ]>

=== MrLoick/architecturerules/src/test/resources/architecture-rules.xml
<?xml version="1.0"?>

<!--<!DOCTYPE architecture SYSTEM
        "http://architecturerules.googlecode.com/svn/trunk/src/main/resources/architecture-rules.dtd">-->

<architecture>

    <configuration>

        <sources no-packages="ignore">
            <source not-found="ignore">core\target\classes</source>
            <source not-found="ignore">util\target\classes</source>
            <source not-found="ignore">parent-pom\target\classes</source>
            <source not-found="ignore">web\target\classes</source>
        </sources>

        <cyclicalDependency test="true"/>

    </configuration>


    <rules>

        <rule>
            <id>dao</id>
            <package>
                com.seventytwomiles.pagerank.core.dao
            </package>
            <violations>
                <violation>
                    com.seventytwomiles.pagerank.core.services
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.core.builder
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.util
                </violation>
            </violations>
            <comment>The dao interface package should rely on nothing.</comment>
        </rule>

        <rule>
            <id>strategy</id>
            <package>
                com.seventytwomiles.pagerank.serviceproviders.startegies
            </package>
            <violations>
                <violation>
                    com.seventytwomiles.pagerank.core.services
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.core.dao.hibernate
                </violation>
            </violations>
            <comment>strategies should be as pluggable as possible</comment>
        </rule>

        <rule>
            <id>model</id>
            <package>
                com.seventytwomiles.pagerank.core.model
            </package>
            <violations>
                <violation>
                    com.seventytwomiles.pagerank.core.dao
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.core.dao.hibernate
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.core.services
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.core.strategy
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.core.builder
                </violation>
                <violation>
                    com.seventytwomiles.pagerank.util
                </violation>
            </violations>
            <comment>model should remain competely isolated</comment>
        </rule>

    </rules>

</architecture>
